### ISSUE TITLE
Preprocessing the image

### ISSUE THREAD

**Issue by dilipkk** [ymcidence/DeepSketchHashing#3]
Hi,
    Could you please include the details of how you pre-processed the image input? Specifically, the scale of image and sketch input, and whether mean subtraction was used. Thanks.

**Comment by sounakdey** [comment]
I have the same question as above... Can you please provide it

**Comment by ymcidence** [comment]
Hi all
The pre-processing procedure is quite close to the one of AlexNet with the same image size (without image duplication). You need to subtract the images and sketches using the mean of data.  Please reproduce the mean for the sketches as they are quite different from real images.

**Comment by dilipkk** [comment]
Hi, thanks a lot. It would be great if you could provide a little clarification. 

1)The input image sizes mentioned in your deploy files are different from 256×256. (200×200 for sketches and 227x227 for images). I am guessing that after mean subtraction, center cropping was used. Right?

2)I am assuming that raw RGB values were used without normalization to a [0,1] range. Hope that's right too.

Also, thanks a lot for maintaining this repo.

**Comment by sghoshcvc** [comment]
Hi, Can you please clarify about mean of sketches?
Did you use the training set to create the mean per pixel for the entire training set like alexnet or mean intensity per sketch is used
